@extends('layouts.app')
@extends('layouts.main.head')
@extends('layouts.main.navigation')
@extends('layouts.main.preload')
@extends('layouts.contact.contacts')
@extends('layouts.contact.form')
@extends('layouts.main.footer')